# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import readability_pb2 as readability__pb2


class ReadabilityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReadableDocument = channel.unary_unary(
                '/readabilitypb.Readability/GetReadableDocument',
                request_serializer=readability__pb2.GetReadableDocumentRequest.SerializeToString,
                response_deserializer=readability__pb2.GetReadableDocumentResponse.FromString,
                )
        self.GetReadinessInfo = channel.unary_unary(
                '/readabilitypb.Readability/GetReadinessInfo',
                request_serializer=readability__pb2.GetReadinessInfoRequest.SerializeToString,
                response_deserializer=readability__pb2.GetReadinessInfoResponse.FromString,
                )


class ReadabilityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReadableDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadinessInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReadabilityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReadableDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadableDocument,
                    request_deserializer=readability__pb2.GetReadableDocumentRequest.FromString,
                    response_serializer=readability__pb2.GetReadableDocumentResponse.SerializeToString,
            ),
            'GetReadinessInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadinessInfo,
                    request_deserializer=readability__pb2.GetReadinessInfoRequest.FromString,
                    response_serializer=readability__pb2.GetReadinessInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'readabilitypb.Readability', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Readability(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReadableDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/readabilitypb.Readability/GetReadableDocument',
            readability__pb2.GetReadableDocumentRequest.SerializeToString,
            readability__pb2.GetReadableDocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReadinessInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/readabilitypb.Readability/GetReadinessInfo',
            readability__pb2.GetReadinessInfoRequest.SerializeToString,
            readability__pb2.GetReadinessInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
