// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type User struct {
	ID         string   `json:"id"`
	DatabaseID int      `json:"databaseId"`
	Delay      int      `json:"delay"`
	Created    int      `json:"created"`
	Karma      int      `json:"karma"`
	About      string   `json:"about"`
	Submitted  []string `json:"submitted"`
}
