name: "Smoke Test"

on:
  workflow_dispatch:
  schedule:
    - cron: '25,55 * * * *'

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install wget -y
          wget https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64 && \
            chmod +x hey_linux_amd64 && \
            sudo mv hey_linux_amd64 /usr/local/bin/hey
      - name: Test
        run: |
          hey -n 20000 -q 100 -c 50 \
          https://hn.hsblhsn.me/images/proxy.jpeg\?src\=https://hn.hsblhsn.me/images/social_preview.jpeg\?title\=ping
